### ISSUE TITLE
draft/label tag is being sent to other clients

### ISSUE THREAD

**Issue by linuxdaemon** [SaberUK/inspircd#2]
Inspircd built from https://github.com/inspircd/inspircd/commit/c6b5da1f6fdb1bc54ebe97ebe3666ad9ae85e99b with this module enabled, sending a `KICK` with a `draft/label` tag, the tag is forwarded to other clients, however it isn't forwarded on `PRIVMSG`, `NOTICE`, or `TAGMSG`

**Comment by SaberUK** [comment]
I'm guessing this is the fault of dodgy logic in `LabeledResponseTag::OnProcessTag`.

**Comment by SaberUK** [comment]
Actually, now that I look at it `LabeledResponseTag::ShouldSendTag` should probably have an IS_LOCAL check on the origin?

**Comment by linuxdaemon** [comment]
Well shouldn't the tag only be sent back to who sent it? not to local users or anything?

**Comment by SaberUK** [comment]
Yeah but its also networked incase a services server wants to respond to something with a label.

**Comment by SaberUK** [comment]
Updated the module and it seems to be okay now?
